In [48]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings("ignore")
import seaborn as sns

In [49]:
df=pd.read_csv("tweets.csv.zip")

In [50]:
df

id  keyword                 location  \
0          0   ablaze                      NaN   
1          1   ablaze                      NaN   
2          2   ablaze            New York City   
3          3   ablaze           Morgantown, WV   
4          4   ablaze                      NaN   
...      ...      ...                      ...   
11365  11365  wrecked  Blue State in a red sea   
11366  11366  wrecked               arohaonces   
11367  11367  wrecked                       🇵🇭   
11368  11368  wrecked           auroraborealis   
11369  11369  wrecked                      NaN   

                                                    text  target  
0      Communal violence in Bhainsa, Telangana. "Ston...       1  
1      Telangana: Section 144 has been imposed in Bha...       1  
2      Arsonist sets cars ablaze at dealership https:...       1  
3      Arsonist sets cars ablaze at dealership https:...       1  
4      "Lord Jesus, your love brings freedom and pard...       0  
...                                                  ...     ...  
11365  Media should have warned us well in advance. T...       0  
11366  i feel directly attacked 💀 i consider moonbin ...       0  
11367  i feel directly attacked 💀 i consider moonbin ...       0  
11368  ok who remember "outcast" nd the "dora" au?? T...       0  
11369     Jake Corway wrecked while running 14th at IRP.       1  

[11370 rows x 5 columns]

In [51]:
df.drop(["id","keyword","location"],axis=1,inplace=True)

In [52]:
df.head(5)

text  target
0  Communal violence in Bhainsa, Telangana. "Ston...       1
1  Telangana: Section 144 has been imposed in Bha...       1
2  Arsonist sets cars ablaze at dealership https:...       1
3  Arsonist sets cars ablaze at dealership https:...       1
4  "Lord Jesus, your love brings freedom and pard...       0

# CLEANING OF TEXT COLUMN.

In [53]:
df["text"]=df["text"].apply(lambda x:" ".join(x.lower() for x in x.split(" ")))

In [54]:
from bs4 import BeautifulSoup

In [55]:
df["text"]=df["text"].apply(lambda x:BeautifulSoup(x).get_text())

In [56]:
import re
df["text"]=df['text'].apply(lambda x:re.sub("https\S+","",x))

In [57]:
pip install nltk

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'C:\Program Files\Python310\python.exe -m pip install --upgrade pip' command.


In [58]:
import nltk

In [59]:
df.sample(9)

text  target
10860                                     lethal weapon        0
1457              some new body bags + only death grips        0
3672   good morning, the service is delayed by a dera...       1
6257   melbourne joins sydney, canberra and hundreds ...       1
1207   just ring ding dong it🤗. it's over in a second...       0
7787                                      obliterate him       0
8718   2 of 6 defendants -- but not joey gibson -- pl...       1
7999                disease outbreak news from the who:        0
3455   and yet, unfortunately many of the city’s heri...       0

In [60]:
from nltk.corpus import stopwords

In [61]:
stopwords=stopwords.words("english")
print(stopwords)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [62]:
df["text"]=df["text"].apply(lambda x:" ".join([x for x in x.split(" ") if x not in stopwords]))

# TO REMOVE NON APLHA CHARACTER.

In [63]:
df["text"]=df["text"].apply(lambda x:" ".join([re.sub("[^A-Za-z]+","",x) for x in nltk.word_tokenize(x)]))

In [64]:
df["text"]=df['text'].apply(lambda x:" ".join([x for x in x.split(" ") if len(x)>2]))

In [65]:
df.sample(10)

text  target
7928   cleaning animals oil spill ducks always darkes...       0
64     iran says shot ukraine international flight ac...       1
9235                love siren mandarin ver untamed boys       0
3595   design could derail charges tied popular rifle...       0
5349   badminton king momota faces two months fatal c...       1
10017  bernie sanders every direct reference israel n...       0
6643   homebrew bounty hunter coworkers went witches ...       0
1235   needs trending whiteophobia sick tired bloody ...       0
3780   nia investigating hadiya love jihadcase nia in...       0
7336                      hans frank mass murderer poles       0

In [66]:
df.head(5)

text  target
0  communal violence bhainsa telangana stones pel...       1
1  telangana section imposed bhainsa january clas...       1
2               arsonist sets cars ablaze dealership       1
3               arsonist sets cars ablaze dealership       1
4  lord jesus love brings freedom pardon fill hol...       0

In [67]:
from nltk.stem import WordNetLemmatizer
lematizer=WordNetLemmatizer()
def lemmatizer_words(text):
    return " ".join([lematizer.lemmatize(word) for word in text.split()])

In [68]:
df['text']=df['text'].apply(lambda text: lemmatizer_words(text))

In [69]:
df.head(5)

text  target
0  communal violence bhainsa telangana stone pelt...       1
1  telangana section imposed bhainsa january clas...       1
2                 arsonist set car ablaze dealership       1
3                 arsonist set car ablaze dealership       1
4  lord jesus love brings freedom pardon fill hol...       0

In [70]:
df["target"].value_counts()

0    9256
1    2114
Name: target, dtype: int64

# SPLITTING DATA

In [71]:
X=df[["text"]]
y=df["target"]

In [72]:
from sklearn.model_selection import train_test_split

In [73]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=18)

In [74]:
print("Train Data",X_train.shape,y_train.shape)

Train Data (9096, 1) (9096,)


In [75]:
print("Test Data",X_test.shape,y_test.shape)

Test Data (2274, 1) (2274,)


# COUNTVECTORIZER

In [76]:
from sklearn.feature_extraction.text import CountVectorizer

In [77]:
vect=CountVectorizer()

In [78]:
X_train_vect=vect.fit_transform(X_train.values.ravel())

In [79]:
X_train_vect

<9096x16857 sparse matrix of type '<class 'numpy.int64'>'
	with 82246 stored elements in Compressed Sparse Row format>

In [80]:
X_test_vect=vect.transform(X_test.values.ravel())

In [81]:
X_test_vect

<2274x16857 sparse matrix of type '<class 'numpy.int64'>'
	with 18231 stored elements in Compressed Sparse Row format>

In [82]:
vect.get_feature_names()

['aaaaaaaaacccccckkkkkkkk',
 'aab',
 'aalaathun',
 'aap',
 'aaron',
 'aaronjayjack',
 'aayega',
 'ab',
 'aba',
 'abaf',
 'abandon',
 'abandoned',
 'abandoning',
 'abated',
 'abbey',
 'abbott',
 'abby',
 'abc',
 'abdel',
 'abdicating',
 'abducted',
 'abduction',
 'abductor',
 'abdullah',
 'abeg',
 'abel',
 'abertillery',
 'abetting',
 'abiding',
 'ability',
 'abj',
 'abject',
 'ablaze',
 'able',
 'abnormal',
 'abnormally',
 'abo',
 'aboard',
 'abomination',
 'abor',
 'aborbitadi',
 'aboriginal',
 'abortion',
 'abou',
 'abounds',
 'about',
 'above',
 'aboveignorance',
 'abrar',
 'abroad',
 'abruptly',
 'absence',
 'absentee',
 'abso',
 'absolute',
 'absolutely',
 'absorb',
 'absorption',
 'abstain',
 'abstained',
 'abstract',
 'absurd',
 'abt',
 'abu',
 'abuja',
 'abukuma',
 'abuse',
 'abused',
 'abuser',
 'abusing',
 'abusive',
 'abvp',
 'abysmal',
 'aca',
 'acacia',
 'academia',
 'academy',
 'acc',
 'acce',
 'accelerate',
 'accelerates',
 'accent',
 'accept',
 'acceptable',
 'acceptanc

# LOGISTIC REGRESSION.

In [83]:
from sklearn.linear_model import LogisticRegression

In [84]:
reg=LogisticRegression()

In [85]:
reg.fit(X_train_vect,y_train)

LogisticRegression()

In [86]:
y_train_pred=reg.predict(X_train_vect)

In [87]:
y_test_pred=reg.predict(X_test_vect)

In [96]:
from sklearn.metrics import classification_report,confusion_matrix

In [89]:
print("Train Data")
print(classification_report(y_train,y_train_pred))
print("Test Data")
print(classification_report(y_test,y_test_pred))

Train Data
              precision    recall  f1-score   support

           0       0.97      1.00      0.98      7400
           1       0.98      0.88      0.93      1696

    accuracy                           0.97      9096
   macro avg       0.98      0.94      0.96      9096
weighted avg       0.97      0.97      0.97      9096

Test Data
              precision    recall  f1-score   support

           0       0.92      0.97      0.94      1856
           1       0.81      0.60      0.69       418

    accuracy                           0.90      2274
   macro avg       0.86      0.79      0.82      2274
weighted avg       0.90      0.90      0.90      2274



In [98]:
confusion_matrix(y_train,y_train_pred)

array([[7374,   26],
       [ 208, 1488]], dtype=int64)

In [99]:
confusion_matrix(y_test,y_test_pred)

array([[1797,   59],
       [ 166,  252]], dtype=int64)

# NAIVE BAYES.

In [90]:
from sklearn.naive_bayes import MultinomialNB

In [91]:
multi_nb=MultinomialNB()

In [92]:
multi_nb.fit(X_train_vect,y_train)

MultinomialNB()

In [93]:
y_train_predict=multi_nb.predict(X_train_vect)
y_test_predict=multi_nb.predict(X_test_vect)

In [95]:
print("Train Data")
print(classification_report(y_train,y_train_predict))
print("Test Data")
print(classification_report(y_test,y_test_predict))

Train Data
              precision    recall  f1-score   support

           0       0.96      0.97      0.97      7400
           1       0.87      0.83      0.85      1696

    accuracy                           0.94      9096
   macro avg       0.91      0.90      0.91      9096
weighted avg       0.94      0.94      0.94      9096

Test Data
              precision    recall  f1-score   support

           0       0.92      0.95      0.94      1856
           1       0.74      0.63      0.68       418

    accuracy                           0.89      2274
   macro avg       0.83      0.79      0.81      2274
weighted avg       0.89      0.89      0.89      2274



In [100]:
confusion_matrix(y_train,y_train_predict)

array([[7182,  218],
       [ 292, 1404]], dtype=int64)

In [102]:
confusion_matrix(y_test,y_test_predict)

array([[1764,   92],
       [ 153,  265]], dtype=int64)